spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/foro_hub}
spring.datasource.username=root
spring.datasource.password=0912
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration



server.port=8080
server.error.include-stacktrace=never

api.security.token.secret = ${JWT_SECRET:12345678}